region              = "ap-south-1"
instance-type       = "t3.large"
availability-zone-1 = "ap-south-1a"
availability-zone-2 = "ap-south-1b"
ec2-volume-type     = "gp2"
ec2-volume-size     = "20"
db-sg-name          = "cg-4-db-sg"
db-subnet           = "cg-4-db-sub-grp"
