apiVersion: v1
kind: Service
metadata:
 name: auth-service
 labels:
   app: keyist-auth-server
spec:
 type: NodePort
 ports:
 - port: 8081
   nodePort: 30081
 selector:
   app: keyist-auth-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: keyist-auth-server
 labels:
   app: keyist-auth-server
spec:
 replicas: 2
 selector:
   matchLabels:
     app: keyist-auth-server
 template:
   metadata:
     labels:
       app: keyist-auth-server
   spec:
     containers:
     - name: keyist-auth-server
       image: kvempali/keyist-authorization-server:latest
       resources:
         limits:
           cpu: 1000m
         requests:
           cpu: 500m
       imagePullPolicy: Always
       ports:
       - containerPort: 8081
       env:
       - name: SPRING_DATASOURCE_URL
         value: jdbc:mysql://terraform-20240510144835569700000005.cvs4iqugy8m9.ap-south-1.rds.amazonaws.com:3306/keyist?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
       - name: SPRING_DATASOURCE_USERNAME
         value: admin
       - name: SPRING_DATASOURCE_PASSWORD
         value: admin123
