# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    # - name: Cache SonarQube packages
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.sonar/cache
    #     key: ${{ runner.os }}-sonar
    #     restore-keys: ${{ runner.os }}-sonar
    # - name: Cache Maven packages
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.m2
    #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: ${{ runner.os }}-m2
    - name: Build & analyse Resource Server with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=capstone-group4-project1-backend --file resource_server/pom.xml
    - name: Build and analyze oAUth Server with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=capstone-group4-project1 --file authorization_server/pom.xml

  docker:
      runs-on: self-hosted
      steps:
        # -
        #   name: Checkout
        #   uses: actions/checkout@v4
        # -
        #   name: Set up QEMU
        #   uses: docker/setup-qemu-action@v3
        # -
        #   name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push Resource Server
          uses: docker/build-push-action@v5
          with:
            context: ./resource_server
            push: true
            tags: kvempali/keyist-resource-server:latest
        -
          name: Build and push Auth Server
          uses: docker/build-push-action@v5
          with:
            context: ./authorization_server
            push: true
            tags: kvempali/keyist-authorization-server:latest
        -
          name: Build and push UI Client
          uses: docker/build-push-action@v5
          with:
            context: ./client
            push: true
            tags: kvempali/keyist-client:latest
