name: terraform-infra-provisioning

on:
  workflow_dispatch:
#  push:
#    branches: [ '*' ]
#    paths-ignore:
#      - '**/README.md'
#  pull_request:
#    branches: ["main"]
#    paths-ignore:
#      - '**/README.md'

permissions: read-all
jobs:
  terraform-plan:
    name: 'continuous-integration'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

  - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ap-south-1

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialise project and view terraform plan
        run: |
          cd cmu-project
          terraform fmt
          terraform init
  terraform-deploy:
    name: 'Terraform-Deploy'
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ap-south-1

              # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
              - name: Setup Terraform
                uses: hashicorp/setup-terraform@v1
              - name: Initialise project and view terraform plan
                run: |
                  cd cmu-project
                  terraform fmt
                  terraform apply
